In [2]:
# 1st
import numpy as np
arr=np.array([1,2,3,4,5])
print("orignal array:",arr)

#a
print("after adding 2:",arr+2)
#b
print("after multiplying by 3:",arr*3)
#c
print("after dividing by 2:",arr/2)

orignal array: [1 2 3 4 5]
after adding 2: [3 4 5 6 7]
after multiplying by 3: [ 3  6  9 12 15]
after dividing by 2: [0.5 1.  1.5 2.  2.5]


In [7]:
#2
import numpy as np
arr=np.array([1,2,3,4,5])
#a
reverse_arr=arr[::-1]
print("original array:",arr)
print("Reversed Array:",reverse_arr)
#b i
x=np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values,counts = np.unique(x,return_counts=True)
values1,counts1 = np.unique(y,return_counts=True)
most_frequent1=values[np.argmax(counts1)]
most_frequent=values[np.argmax(counts)]
indices=np.where(x==most_frequent)[0]
indices1=np.where(y==most_frequent1)[0]
print("most frequent value:",most_frequent)
print("most frequent value for y:",most_frequent1)
print("indices of most frequent value:",indices)
print("indices of most frequent value for y:",indices1)

original array: [1 2 3 4 5]
Reversed Array: [5 4 3 2 1]
most frequent value: 1
most frequent value for y: 1
indices of most frequent value: [0 5 7 8 9]
indices of most frequent value for y: [0 1 2]


In [8]:
#3
import numpy as np
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]

])
# a
print("1st row, 2nd column:",arr[0,1])
# b
print("3rd row 1st column:",arr[2,0])




1st row, 2nd column: 20
3rd row 1st column: 70


In [9]:
import numpy as np

# Create 1-D NumPy array with 25 evenly spaced numbers from 10 to 100
paryag = np.linspace(10, 100, 25)

print("Array:", paryag)

# Print dimensions
print("Dimensions:", paryag.ndim)

# Print shape
print("Shape:", paryag.shape)

# Print total number of elements
print("Total Elements:", paryag.size)

# Print data type
print("Data Type:", paryag.dtype)

# Print total number of bytes
print("Total Bytes:", paryag.nbytes)

# Find transpose using reshape()
transpose = paryag.reshape(1, 25).T

print("Transpose using reshape():")
print(transpose)

# Find transpose using T attribute
print("Transpose using T:")
print(paryag.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [10]:
import numpy as np

# Create a 2-D array with 3 rows and 4 columns
ucs420_paryag = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_paryag)

# Mean
print("Mean:", np.mean(ucs420_paryag))

# Median
print("Median:", np.median(ucs420_paryag))

# Maximum
print("Maximum:", np.max(ucs420_paryag))

# Minimum
print("Minimum:", np.min(ucs420_paryag))

# Unique elements
print("Unique Elements:", np.unique(ucs420_paryag))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_paryag = ucs420_paryag.reshape(4, 3)

print("Reshaped Array (4 x 3):")
print(reshaped_ucs420_paryag)

# Resize to 2 rows and 3 columns
resized_ucs420_paryag = np.resize(ucs420_paryag, (2, 3))

print("Resized Array (2 x 3):")
print(resized_ucs420_paryag)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
