In [16]:
#1
import numpy as np
temperature = np.array([25,28,31,35,38,27,33,40])
#a
corrected = temperature + 2
print(corrected)
#b
f = (9*corrected)/5 + 32
print(f)
#c
high = corrected > 32
hot_readings = corrected[high]
print("High:", high)
print("Readings > 32°C:", hot_readings)
#d
print(high.sum())
#e
#Vectorization and Boolean indexing push the looping into NumPy's fast, compiled C code

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
High: [False False  True  True  True False  True  True]
Readings > 32°C: [33 37 40 35 42]
5


In [19]:
#2
import numpy
steps= np.array([[5000,6200,7100],[8000,7500,9000],[4500,5100,4800],[9000,8500,9500]])
#a
print(steps.sum())
#b
print(steps.mean())
#c
print(steps.max())
print(steps.min())
#d
steps_per_day = np.sum(steps, axis=0)
print("Total steps per day:", steps_per_day)
#e
steps_per_user = np.sum(steps, axis=1)
print("Total steps per user:", steps_per_user)
#f
max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of max steps (user, day):", max_position)
print("Max value at that position:", steps[max_position])


84200
7016.666666666667
9500
4500
Total steps per day: [26500 27300 30400]
Total steps per user: [18300 24500 14400 27000]
Position of max steps (user, day): (np.int64(3), np.int64(2))
Max value at that position: 9500


In [24]:
#3
import numpy as np

# a.
original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original array:", original)

# b.
subset = original[1:4]
print("\nb. Subset (original[1:4]):", subset)

# c.
subset[0] = 999
print("\nc. After modifying subset[0] = 999:")
print("   original:", original)
print("   subset  :", subset)

# d.
subset_copy = original[1:4].copy()
subset_copy[0] = 500
print("\nd. After modifying subset_copy[0] = 500 (using .copy()):")
print("   original    :", original)
print("   subset_copy :", subset_copy)

# e.
matrix = np.arange(1, 13).reshape(3, 4)
print("\ne. 3x4 Matrix:\n", matrix)

# f.
first_row = matrix[0, :]
last_row = matrix[-1, :]
second_col = matrix[:, 1]
sub_block = matrix[0:2, 1:3]

print("\nf. First row       :", first_row)
print("   Last row        :", last_row)
print("   Second column   :", second_col)
print("   Rows1-2,Cols2-3 :\n", sub_block)

# g.
flat_copy = matrix.flatten()
flat_view = matrix.ravel()
print("\ng. flatten():", flat_copy)
print("   ravel()  :", flat_view)

#
flat_view[0] = -100
print("\nh. After modifying ravel()[0] = -100:")
print("   flat_view (ravel):", flat_view)
print("   original matrix :\n", matrix)
print("   -> ravel() returns a VIEW, so the original matrix IS affected.")

# i.
flat_copy[1] = -200
print("\ni. After modifying flatten()[1] = -200:")
print("   flat_copy (flatten):", flat_copy)
print("   original matrix   :\n", matrix)
print("   -> flatten() returns a COPY, so the original matrix is NOT affected.")

# j.
print("\nj. Matrix properties:")
print("   Shape :", matrix.shape)
print("   ndim  :", matrix.ndim)
print("   size  :", matrix.size)
print("   dtype :", matrix.dtype)

a. Original array: [1 2 3 4 5 6]

b. Subset (original[1:4]): [2 3 4]

c. After modifying subset[0] = 999:
   original: [  1 999   3   4   5   6]
   subset  : [999   3   4]

d. After modifying subset_copy[0] = 500 (using .copy()):
   original    : [  1 999   3   4   5   6]
   subset_copy : [500   3   4]

e. 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

f. First row       : [1 2 3 4]
   Last row        : [ 9 10 11 12]
   Second column   : [ 2  6 10]
   Rows1-2,Cols2-3 :
 [[2 3]
 [6 7]]

g. flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   ravel()  : [ 1  2  3  4  5  6  7  8  9 10 11 12]

h. After modifying ravel()[0] = -100:
   flat_view (ravel): [-100    2    3    4    5    6    7    8    9   10   11   12]
   original matrix :
 [[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
   -> ravel() returns a VIEW, so the original matrix IS affected.

i. After modifying flatten()[1] = -200:
   flat_copy (flatten): [   1 -200    3    4    5    6    7    8    9 

In [23]:
#4
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

# a.
print("Shape:", X.shape)
print("ndim :", X.ndim)

# b.
print("\nX.T:\n", X.T)

# c.
XtX = X.T @ X
print("\nX.T @ X:\n", XtX)

# d.
XtX_inv = np.linalg.inv(XtX)
print("\nInverse of (X.T @ X):\n", XtX_inv)

# e.
beta = XtX_inv @ X.T @ y
print("\nCoefficients (beta):", beta)

# g.
new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("\nPredicted assistance score:", predicted_score)

Shape: (4, 3)
ndim : 2

X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of (X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

Coefficients (beta): [-0.15921454  0.14083853 10.06302242]

Predicted assistance score: 75.27862544779117
